# fly.toml app configuration file generated for imagemagic on 2023-06-05T01:23:44+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "imagemagic"
primary_region = "sin"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
